
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ssjlwloypbpheolyjjqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzamx3bG95cGJwaGVvbHlqanF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNjQyOTEsImV4cCI6MjA2MDk0MDI5MX0.vfTvV1bnpbNc7G6cLCxAg2zj_JC9EhgKkPbgSF9fxo0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
